import { Product } from "../types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    nameBn: "ধান (আমন)",
    nameEn: "Rice (Amon)",
    category: "ধান",
    price: 52,
    unit: "কেজি",
    quantity: 250,
    farmer: "মোঃ রহিম",
    location: "গাজীপুর",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    description: "সম্পূর্ণ রাসায়নিক মুক্ত তাজা আমন ধান, সরাসরি মাঠ থেকে সংগৃহীত।",
  },
  {
    id: 2,
    nameBn: "লাল আলু",
    nameEn: "Red Potato",
    category: "সবজি",
    price: 32,
    unit: "কেজি",
    quantity: 500,
    farmer: "আব্দুল কুদ্দুস",
    location: "মুন্সীগঞ্জ",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80",
    description: "মুন্সীগঞ্জের বিখ্যাত সুস্বাদু লাল আলু। দীর্ঘস্থায়ী সংরক্ষণ উপযোগী।",
  },
  {
    id: 3,
    nameBn: "পাকা টমেটো",
    nameEn: "Fresh Tomato",
    category: "সবজি",
    price: 45,
    unit: "কেজি",
    quantity: 180,
    farmer: "হাফিজুর রহমান",
    location: "বগুড়া",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80",
    description: "বগুড়ার নিজস্ব ক্ষেতের তাজা ও রসালো লাল টমেটো।",
  },
  {
    id: 4,
    nameBn: "দেশি পেঁয়াজ",
    nameEn: "Local Onion",
    category: "সবজি",
    price: 68,
    unit: "কেজি",
    quantity: 400,
    farmer: "সোরহাব হোসেন",
    location: "ফরিদপুর",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80",
    description: "ফরিদপুরের ঝাঁঝালো ও গুণসম্পন্ন খাঁটি দেশি পেঁয়াজ।",
  },
  {
    id: 5,
    nameBn: "গম",
    nameEn: "Wheat Grains",
    category: "শস্য",
    price: 48,
    unit: "কেজি",
    quantity: 300,
    farmer: "কামরুল হাসান",
    location: "রাজশাহী",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    description: "উচ্চ প্রোটিন সমৃদ্ধ রাজশাহীর তাজা গম।",
  },
  {
    id: 6,
    nameBn: "হিমসাগর আম",
    nameEn: "Himsagar Mango",
    category: "ফল",
    price: 120,
    unit: "কেজি",
    quantity: 150,
    farmer: "এম এ সাত্তার",
    location: "চাঁপাইনবাবগঞ্জ",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80",
    description: "চাঁপাইনবাবগঞ্জের বিখ্যাত মিষ্টি ও সুবাসিত হিমসাগর আম।",
  },
  {
    id: 7,
    nameBn: "কাঁচা মরিচ",
    nameEn: "Green Chili",
    category: "মসলা",
    price: 110,
    unit: "কেজি",
    quantity: 90,
    farmer: "নুরুল ইসলাম",
    location: "পাবনা",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1588879460418-49800db758e5?auto=format&fit=crop&w=600&q=80",
    description: "ঝাঁঝালো তাজা কাঁচা সবুজ মরিচ। সরাসরি জমি থেকে তোলা।",
  },
  {
    id: 8,
    nameBn: "গোল বেগুন",
    nameEn: "Eggplant",
    category: "সবজি",
    price: 38,
    unit: "কেজি",
    quantity: 220,
    farmer: "তরিকুল ইসলাম",
    location: "রংপুর",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    description: "নরম বীজহীন দেশি চারা গোল বেগুন।",
  },
];
